grammar org.xtext.example.bug508810.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

generate myDsl "http://www.xtext.org/example/bug508810/mydsl/MyDsl"
import "http://www.eclipse.org/emf/2002/Ecore" as ecore


Model:
	greetings+=Greeting*;

Greeting:
	'Hello' name=ID '!'
	parameters+=Parameter*;

Parameter returns ecore::EStringToStringMapEntry:
	{ecore::EStringToStringMapEntry}
	(key=ID '=' value=ID);
