/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.bug508810.mydsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDslScopeProvider extends DelegatingScopeProvider {
}
